docker_network: 172.17.0.1

im:
  url:
    base: http://${docker_network}:6001
    sendmsgsync: ${im.url.base}/onMessageSync

sra:
  url:
    base: http://${docker_network}:6004
    audit:
      findbyflow: ${sra.url.base}/audit/findByCloned?id={id}
      findbydate2: ${sra.url.base}/audit/findByDate2
  product: IM


eddie:
  url:
    base: http://${docker_network}:6008
    sendmsg: ${eddie.url.base}/onMessage
    sendmsgsync: ${eddie.url.base}/sendMessageSync
flow:
  url:
    base: http://${docker_network}:6005
    sendmsg: ${flow.url.base}/api/sendMessage
    sendmsgsync: ${flow.url.base}/api/sendMessageSync